---
abstract: 'Perl interface to the CyberSource Simple Order SOAP API'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  DateTime: 0
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Module::Runtime: 0
  Test::Fatal: 0
  Test::Moose: 0
  Test::More: 0.88
  Test::Requires: 0
  Test::Requires::Env: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-CyberSource
no_index:
  file:
    - perlcritic.rc
requires:
  Class::Load: 0.20
  Config: 0
  DateTime::Format::W3CDTF: 0.06
  Exception::Base: 0
  File::ShareDir::ProjectDistDir: 0
  LWP::Protocol::https: 0
  Module::Load: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::ABC: 0.06
  MooseX::AbstractFactory: 0
  MooseX::Aliases: 0
  MooseX::RemoteHelper: 0
  MooseX::RemoteHelper::CompositeSerialization: 0
  MooseX::SetOnce: 0.200001
  MooseX::StrictConstructor: 0
  MooseX::Types: 0
  MooseX::Types::Common::Numeric: 0.001003
  MooseX::Types::Common::String: 0.001005
  MooseX::Types::CreditCard: 0.002
  MooseX::Types::DateTime: 0
  MooseX::Types::DateTime::W3C: 0
  MooseX::Types::Email: 0
  MooseX::Types::Locale::Country: 0
  MooseX::Types::Locale::Currency: 0
  MooseX::Types::Moose: 0
  MooseX::Types::NetAddr::IP: 0
  MooseX::Types::Path::Class: 0
  Try::Tiny: 0
  XML::Compile::SOAP11: 0
  XML::Compile::SOAP::WSS: 1.04
  XML::Compile::Transport::SOAPHTTP: 0
  XML::Compile::WSDL11: 0
  namespace::autoclean: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/hostgator/business-cybersource/issues
  homepage: https://metacpan.org/release/Business-CyberSource
  repository: git://github.com/hostgator/business-cybersource.git
version: 0.007007
