
BEGIN {
  unless ($ENV{AUTHOR_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for testing by the author');
  }
}

# This test is generated by Dist::Zilla::Plugin::Test::PodSpelling
use strict;
use warnings;
use Test::More;
use Test::Requires {
    'Test::Spelling'  => 0.12,
    'Pod::Wordlist::hanekomu' => 0,
};


add_stopwords(<DATA>);
all_pod_files_spelling_ok('bin', 'lib');
__DATA__
SubmittingPatches
CyberSource
CyberSource's
Num
Str
datetime
merchantID
ip
DCC
cid
cvn
cvc
cvv
login
AuthReversal
SOAPI
Bleue
Carta
Carte
Dankort
JAL
Santander
UATP
YYYY
timestamp
overmeer
ACKNOWLEDGEMENTS
AVS
MerchantReferenceCode
Caleb
Cushing
lib
Business
Request
FollowOnCredit
Role
Response
Authorization
Currency
BusinessRules
PurchaseInfo
MooseX
Types
Credit
BillingInfo
CVN
Accept
ProcessorResponse
Items
ReconciliationID
Common
CreditCardInfo
Credentials
ForeignCurrency
StandAloneCredit
Sale
FollowUp
Capture
RequestID
