
BEGIN {
  unless ($ENV{AUTHOR_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for testing by the author');
  }
}

use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.002004
eval "use Test::Spelling 0.12; use Pod::Wordlist::hanekomu; 1" or die $@;


add_stopwords(<DATA>);
all_pod_files_spelling_ok('bin', 'lib');
__DATA__
CyberSource's
Num
Str
datetime
merchantID
ip
DCC
cid
cvn
cvc
cvv
login
SOAPI
Bleue
Carta
Carte
Dankort
JAL
Santander
UATP
YYYY
timestamp
overmeer
AVS
MerchantReferenceCode
env
WSDL
XSD
subclasses
Caleb
Cushing
lib
Business
CyberSource
Message
Factory
Request
Role
Currency
BusinessRules
AuthReversal
Authorization
Response
CVN
ProcessorResponse
ReconciliationID
Common
Credentials
CreditCard
StandAloneCredit
FollowUp
Capture
RequestID
FollowOnCredit
Client
PurchaseInfo
MooseX
Types
Credit
BillingInfo
Accept
Items
CreditCardInfo
ForeignCurrency
Sale
